### ISSUE TITLE
Walltime

### ISSUE THREAD

**Issue by gdevenyi** [pipitone/qbatch#10]
Somehow I missed there's no walltime option in this version, add?

**Comment by gdevenyi** [comment]
So I now see in the examples that you can add it on the command line as an option added to the end.

While nice, this makes it less flexible than the original qbatch for the purposes of scripting.

Thoughts?

**Comment by pipitone** [comment]
Yes, I think so. Perhaps `-t,--walltime`.

**Comment by gdevenyi** [comment]
Same goes as #5 if we support walltime as part of qbatch, the exact batching system can be abstracted away.
