### ISSUE TITLE
--advanced-help option to show help for advanced options, but hide it otherwise

### ISSUE THREAD

**Issue by pipitone** [pipitone/qbatch#100]
What do you think about by default just showing the key qbatch options so that the display is simple and not overwhelming for newbies to qbatch, but an `--advanced-help` option to show everything for power users?

**Comment by gdevenyi** [comment]
Rather than this, how about running "qbatch" by itself giving a shortened help, and "qbatch --help" giving the full help, I think that's the "UNIX Way"

**Comment by pipitone** [comment]
I like it.
