### ISSUE TITLE
--no-env causes failure if gnu parallel is loaded from a module

### ISSUE THREAD

**Issue by pipitone** [pipitone/qbatch#102]
Rather obvious but not intuitive for newcomers, especially because there is no warning from qbatch.

**Comment by gdevenyi** [comment]
Perhaps a warning should be printed for --no-env

**Comment by pipitone** [comment]
We could also stick a check for parallel at the start of the job script, e.g. 

```sh
which parallel || { echo "GNU parallel not found. Exiting."; exit 1; }
```

**Comment by gdevenyi** [comment]
Hrm, I like that, just need to keep an eye on my new "don't use parallel for single commands" modifications (see PR #108)

**Comment by gdevenyi** [comment]
"Fixed" by adding a reasonable job error in the script
