### ISSUE TITLE
Prep for 1.1 release?

### ISSUE THREAD

**Issue by gdevenyi** [pipitone/qbatch#117]
I've pushed a bunch of changes since 1.0.1.

What do you want to see finished before 1.1?

I will tag what I want finished.

**Comment by pipitone** [comment]
Thanks @gdevenyi. I've added the `--no-env` bug to the list, but otherwise looks fine (except we could perhaps leave out the conda package #77 since pypi is an easy install? no biggie).

I'm mostly away until August so won't be working on qbatch until then.
