### ISSUE TITLE
--depend fails on Python 2.6 because subprocess.check_output doesn't exist

### ISSUE THREAD

**Issue by pipitone** [pipitone/qbatch#118]
Title says it all; [subprocess.check_output](https://docs.python.org/2.7/library/subprocess.html#subprocess.check_output) was added in python 2.7. Ugh. 

All in favour of not supporting python 2.6 say :+1:

**Comment by andrewjanke** [comment]
+1 python3  or go home.


a

**Comment by gdevenyi** [comment]
We can totally drop 2.6 support, I think it's out of maintenance

**Comment by pipitone** [comment]
Removed python 2.6 mentions in de97d67
