### ISSUE TITLE
Detect/check queuing system

### ISSUE THREAD

**Issue by pipitone** [pipitone/qbatch#133]
If jobs are submitted and the wrong queuing system is specified, the error messages returned aren't particularly helpful at the moment (see #57). Perhaps we can detect what the queuing system is, or verify that it has been set correctly when `qbatch` is run, or print more helpful error messages when a job is run under an incompatible queuing system.

**Comment by gdevenyi** [comment]
FSL uses SGE_ROOT to detect SGE.

**Comment by gdevenyi** [comment]
PBS_DEFAULT seems like it may be a reasonable PBS detection method.

**Comment by gdevenyi** [comment]
``pbs-config --libs`` is suggested on torque mailing list
