### ISSUE TITLE
compute_threads with ppj > 1 and SGE breaks due to string

### ISSUE THREAD

**Issue by gdevenyi** [pipitone/qbatch#137]
Fails here
https://github.com/pipitone/qbatch/blob/master/bin/qbatch#L483

Due to redefining ppj for SGE at:
https://github.com/pipitone/qbatch/blob/master/bin/qbatch#L455

Easy solution is to use args.ppj at 483

**Comment by dcoynel** [comment]
Should this also be corrected at L515, in the other call of compute_threads ?

**Comment by gdevenyi** [comment]
It doesn't need to be, as ppj isn't rewritten in that code path.

**Comment by gdevenyi** [comment]
Oh shoot, I did totally miss a codepath, fix coming.

**Comment by gdevenyi** [comment]
Fixed now, please try again!
