### ISSUE TITLE
logfiles without hand-made job names simply overwrite previous logs

### ISSUE THREAD

**Issue by bcdarwin** [pipitone/qbatch#146]
```
$ echo 'echo hello' | qbatch -
Submitted batch job 7650
$ cat logs/slurm-STDIN.out 
hello
$ echo 'echo goodbye' | qbatch -
Submitted batch job 7651
$ cat logs/slurm-STDIN.out 
goodbye
```

**Comment by gdevenyi** [comment]
Hrm, this seems like a slurm issue. Both SGE and PBS name their logfiles with a suffix of their jobID.

Will look into controlling naming of logfiles

**Comment by gdevenyi** [comment]
Looks like our logfile naming is overriding the inclusion of a jobid specs, will fix
https://github.com/pipitone/qbatch/blob/master/bin/qbatch#L549

**Comment by gdevenyi** [comment]
Thanks for the good catch. We're not actively using SLURM yet, so I expect there to be some more tweaks to be done here.
