### ISSUE TITLE
warning message about missing sbatch - using qbatch 1.0.1

### ISSUE THREAD

**Issue by mcvaneede** [pipitone/qbatch#148]
We use qbatch 1.0.1 on a system that does not have sbatch installed. qbatch properly submits jobs to the queue (MOAB), but does produce an error message that gives users the sense that something went wrong:

which: no sbatch in (.../many/paths/...)

Perhaps if sbatch is not required to submit jobs, this message can be suppressed?

**Comment by bcdarwin** [comment]
Probably just send stderr to /dev/null [here](https://github.com/pipitone/qbatch/blob/master/bin/qbatch#L33) ... weird that stdout would do the trick in some system configurations but not everywhere.

**Comment by pipitone** [comment]
@bcdarwin Agreed. Would be clearer to me to move [that whole code block that determines the queuing system](https://github.com/pipitone/qbatch/blob/master/bin/qbatch#L32-L41) into the `main()` method so we can use the `which()` method rather than rely on the system `which`.

**Comment by gdevenyi** [comment]
Fixed by afa1a5052b2877b942d979facf5293f58e5e79b8
