### ISSUE TITLE
setup.py needs to list dependencies properly

### ISSUE THREAD

**Issue by pipitone** [pipitone/qbatch#179]
It's currently possible to install qbatch with python2. Here is [one way of enforcing python versions in setup.py](https://stackoverflow.com/questions/19534896/enforcing-python-version-in-setup-py). 

Should also update the `classifiers` in setup.py to reflect this.

**Comment by gdevenyi** [comment]
Looks like I should have the requirements in both places..?

https://stackoverflow.com/questions/43658870/requirements-txt-vs-setup-py

**Comment by gdevenyi** [comment]
Fixed by #181
