### ISSUE TITLE
Defaults from environment variables

### ISSUE THREAD

**Issue by pipitone** [pipitone/qbatch#21]
Let `qbatch` look to environment variables (e.g. `QBATCH_SYSTEM=PBS`) to override the hardcoded defaults for command-line options. This will make it possible to install and customize `qbatch` to a particular system without having to modify the code to set sensible defaults.

**Comment by gdevenyi** [comment]
Isn't that already in there? Or is that just a skeleton that hasn't been tested?

**Comment by pipitone** [comment]
Yeah, I'm just an idiot. ;-) 

(That's what I get for using github at 4am, btw)
