### ISSUE TITLE
Manage job environment sensibly

### ISSUE THREAD

**Issue by pipitone** [pipitone/qbatch#25]
See #23 in which @gdevenyi notes: 

> Turns out we've been taxing scinet with [environment inheriting (e.g. the `-V` flag)], might be causing some hard-to-trace errors.
> ... we should probably make "-V" optional somehow, to allow for either method.
> Alternatively, we could do our own environment support, perhaps dump the user's environment to a script and then source it on job run?

**Comment by pipitone** [comment]
I like the idea of dumping the environment into the script a la `sge_batch` since it makes for a clean record of the job environment. I'm not a fan of putting this into a separate file though since it might get out of sync/lost; I'd rather it all self-contained. 

What about this: 
- Default to dumping the environment to the script ourselves like `sge_batch` does. 
- Provide a `--no-inherit` option that disables this feature.

**Comment by gdevenyi** [comment]
Not sure what sge_batch is, can you point at it?

I'm guessing it captures the environment and then embeds it in the job? I agree, that makes more sense than the separate file.

Would we also stop running a bash login shell?

**Comment by pipitone** [comment]
Ah, good ol' [`sge_batch`](https://github.com/Mouse-Imaging-Centre/minc-stuffs/blob/master/perl/sge_batch). Thanks NASA. I'm surprised you haven't used it. 

> Would we also stop running a bash login shell?

Yeah, I think we can stop doing this either way.

**Comment by gdevenyi** [comment]
Oh yeah that, I remember hacking on that to get earlier versions of pydpiper to work here. Man perl scripts are ugly.

os.environ.data gives a nice dict of all keypairs, we just need to reformat and save that into a bash export command.

**Comment by gdevenyi** [comment]
Awesome.

Now I need to figure out how to update submodules in a repo...
