### ISSUE TITLE
Passing qsub options should be easier

### ISSUE THREAD

**Issue by pipitone** [pipitone/qbatch#28]
At the moment, in order to pass an option to qsub, you need to include the expected comment prefix characters (e.g. `#PBS`), but this seems counter-intuitive and ugly to me and others that have been using qbatch. @gdevenyi, it seems you also want the capability to run arbitrary commands at the head of a script, so the question is how to allow for both of these things without cluttering the UI. 

How about this UI: 

```
Usage: 
    qbatch [options] <script>

Options: 
    -e,--extra_opt OPTION     A string containing custom options for the queuing system. 
                              For example, --extra_opt "-l vf=8G". This option can be given 
                              multiple times. 

    --header STRING           A string that will be inserted verbatim at the start of the 
                              script. This can be used to insert commands that will be run 
                              once per job. This option can be given multiple times.
   
    ...
```

**Comment by gdevenyi** [comment]
That works fine for me. I prefer positional arguments.
