### ISSUE TITLE
Dry run should be a bit more verbose

### ISSUE THREAD

**Issue by gdevenyi** [pipitone/qbatch#30]

**Comment by gdevenyi** [comment]
Using dry run probably means the user wants to see what qbatch would do.

Should echo the commands it would run instead of running them.

**Comment by pipitone** [comment]
Are you thinking here of echoing the `qsub` command(s) in the case of PBS/SGE?

**Comment by gdevenyi** [comment]
Yes, that or echoing the bash call of the script file

**Comment by gdevenyi** [comment]
Fixed by PR #69
