### ISSUE TITLE
Create tests 

### ISSUE THREAD

**Issue by pipitone** [pipitone/qbatch#32]
We should have some basic tests, but I'm not quite sure how to go about doing that in this case. Thoughts?

**Comment by gdevenyi** [comment]
Check if Travis can simulate PBS and sge?

**Comment by pipitone** [comment]
Great idea Gabe! Looks like Travis CI allows us to [install dependencies from apt](https://docs.travis-ci.com/user/installing-dependencies/) so this looks doable. I'm not very familiar with Travis CI, so this will take some playing around. 

I think we should decide on a minimal set of tests to create for v1.0. Here are mine:  
- reading commands from a file vs. stdin (same output modulo default job name)
- commands are properly chunked for -c=0,1,2,10000 (set `PBS_TASK_ID` and run, check expected commands have run)
- creating array vs individual jobs vs local (identical output)

What would you add?

**Comment by gdevenyi** [comment]
Running commands for the local executor.

Testing the environment setting.

Testing command line setting?

**Comment by gdevenyi** [comment]
Could we use this Travis featureset to test lsf or slurm integration?

**Comment by gdevenyi** [comment]
Test logfile generation/location

**Comment by pipitone** [comment]
As you can see, I've created a few tests to try out travis CI. Getting SGE/PBS/Slurm/etc.. set up on Travis looks doable, but perhaps [more complicated](https://gist.github.com/dan-blanchard/6586533) than we need for 1.0 (but @gdevenyi, give it a shot if you like). 

I'm going to suggest that, for now, we mock the cluster environment by running the job scripts locally as I've done already. To ship, how about we focus on testing that the jobs with different settings (chunk, proc, array/individual, stdin/file) produce expected output, and that the wiring of environment vars and cli options works as expected where easily testable.

**Comment by pipitone** [comment]
I'm going to say the integration tests we have now are good enough to get started. Let me know if you disagree and I'll reopen.
