### ISSUE TITLE
More readable script templating 

### ISSUE THREAD

**Issue by pipitone** [pipitone/qbatch#33]
This is an issue purely to let you know about the `cleanup` branch in which I took a stab at cleaning up the script generation code a bit. So far it's just moving the template into global variables and using `**vars()` in the format call to see if this makes the code more readable. Let me know what you think or if you have any other ideas for readability.

**Comment by gdevenyi** [comment]
I was indeed thinking about how the templating was getting out of hand. Will take a look at the rewrite.

**Comment by gdevenyi** [comment]
I like the new templating. It exposes the template up front and allows for edits quite a bit more clearly

I haven't seen the vars** thing before, and google isn't helping much.

Do you have a reference as to what that's doing?

**Comment by pipitone** [comment]
https://docs.python.org/2/library/functions.html#vars

It's returning the symbol table as a dictionary, and `**vars()` passes that dictionary to the function as named arguments. It's quick and dirty way of formatting a string using whatever variables are defined in scope. It's similar to what bash does with variable expansion inside strings. If we use this sort of kickflip, it deserves a nice comment. :-)
