### ISSUE TITLE
Add setup.py 

### ISSUE THREAD

**Issue by pipitone** [pipitone/qbatch#34]

**Comment by gdevenyi** [comment]
I'm okay with this, as long as the script will always run manually with no install

**Comment by pipitone** [comment]
> I'm okay with this, as long as the script will always run manually with no install

Agreed. I thought about using docopt/click for argument handling, but
I'd rather keep this dead simple. :-)

I want a setup.py so that we can make it dead easy for people to
install, and also so we can put this up on pypi.

**Comment by gdevenyi** [comment]
Ah yes, pypy, I thought that might be where  this was going.

Should we be considering py3 compliance?

**Comment by pipitone** [comment]
Good idea re py3 compliance, see #37. I've not included it for v1.0  but take a crack at it if you'd like. Should be easy.
