### ISSUE TITLE
Check for nonsense numerical options?

### ISSUE THREAD

**Issue by gdevenyi** [pipitone/qbatch#38]
Should we check for nonsense or incompatible chunk, ppn, and processes?

Should we allow negative numbers to set no limit?

Or should we allow users to do dumb things and let qsub complain?

**Comment by pipitone** [comment]
I think we can check for nonsense chunk, ppn, and processes at the very least. I think for walltime and workdir/logdir , etc we can just let the user do dumb things. 

w.r.t to "no limit" settings... I can see that for chunk size (e.g. 0 or -1 would do), processes (parallel uses 0 for no limit, and -ve numbers to use few than available cores). 

I'm not sure that ppn can be <= 0 for any system, but perhaps if it's 0 we don't set it?

**Comment by gdevenyi** [comment]
Didn't realize that about parallel, that's super helpful, we should definitely allow those numbers.

For sge I'm already using ppn > 1 to trigger parallel environment so that makes some sense. Might make the template even uglier for PBS.

We should document in #36 how special numbers work

**Comment by gdevenyi** [comment]
I'd like to expose parallel's default of any many jobs as processors, should we allow for an explicit blank chunk?

All the numbers have defined uses already

**Comment by pipitone** [comment]
Setting -j to 0 will allow as many parallel processes to run in a job as there are processors. I'm not sure what you mean by "blank chunk"

**Comment by gdevenyi** [comment]
If I run parallel on the command line without the "-j" option, I get one job launch per CPU.

I'd like to expose that somehow to qbatch, so I was thinking ``-c ""``. Does that make sense?

**Comment by pipitone** [comment]
Sorry, I'm still confused. Isn't "-j 0" the default, and so its equivalent to not including the -j option?

**Comment by gdevenyi** [comment]
From the manpage:
```
      -j N
       --max-procs N
       -P N     Number of jobslots. Run up to N jobs in parallel.  0 means as many as possible. Default is 100% which will run one job per CPU core.
```

**Comment by pipitone** [comment]
I'm daft. I had read the man page before, but had to try this out on the command line to understand it. "as many as possible" truly means parallel will attempt to run as many commands as it can in parallel, oversubscribing the cores in the process. 

It looks like you can give a -j a percentage, so -j100% uses all available cores. Since we don't actually use -j as an integer, we can relax that requirement and just pass on whatever the user specifies.

**Comment by gdevenyi** [comment]
cool, that works.

Other thing I saw in parallel which might be useful:
```
       --use-cpus-instead-of-cores
                Count the number of physical CPUs instead of CPU cores. When computing how many jobs to run simultaneously relative to the number of CPU cores you can ask GNU parallel to instead look at the number of physical CPUs. This will make sense for
                computers that have hyperthreading as two jobs running on one CPU with hyperthreading will run slower than two jobs running on two physical CPUs. Some multi-core CPUs can run faster if only one thread is running per physical CPU. Most users will
                not need this option.
```

Need to test, but for certain jobs this really makes sense.

Thoughts?

**Comment by pipitone** [comment]
Hmm... maybe we have an option to send options directly to parallel?  

Let's hold off on this or --use-cpus-instead-of-cores until we have a
good use case.
