### ISSUE TITLE
Remove bash login flag from scripts?

### ISSUE THREAD

**Issue by gdevenyi** [pipitone/qbatch#39]
With environment saving should we make sure we start with a clean environment?

**Comment by pipitone** [comment]
I hate this aspect of bash/environment-modules. ;-) 

I do think we can just use plan old `/bin/bash` now but perhaps pull the shebang line up into a constant at the start of the script so that sysadmins can edit it if needs be.

**Comment by gdevenyi** [comment]
I figure some weirdos might want another shell type....

Are we POSIX compliant?
