### ISSUE TITLE
Should qbatch read from STDIN if a file isn't specified?

### ISSUE THREAD

**Issue by pipitone** [pipitone/qbatch#40]
Small usability question: right now we use `-` to indicate that commands are coming from stdin, but lots of programs (`grep`, `sed`, `cat`, ...) will automatically read from stdin if an input file isn't specified. I'm marginally in favour of this for its simplicity, but wanted to see if @gdevenyi has strong opinions on this before I make the change. :-)

**Comment by gdevenyi** [comment]
Making it closer to classic UNIX functions is aok with me.
