### ISSUE TITLE
Incorporate pbs_jobnames into qbatch

### ISSUE THREAD

**Issue by pipitone** [pipitone/qbatch#46]
There is no need to have `pbs_jobnames` as a separate script. We can create a helper function inside the qbatch module for this instead. This will make it possible for people to use qbatch without having to set up their PATH to point to bin/ if they so wish.

**Comment by gdevenyi** [comment]
Hrm.  Most definitely the case. Good call. May even want to parse the xml to find the job names directly rather than text manipulation

**Comment by pipitone** [comment]
It looks like it already parses XML!

**Comment by gdevenyi** [comment]
I mean use the xml search tools to find the job is,  rather than dumping and searching afterwards :)
