### ISSUE TITLE
Preflight check for parallel and other dependencies

### ISSUE THREAD

**Issue by pipitone** [pipitone/qbatch#47]
It would be nice if qbatch [checked](http://stackoverflow.com/questions/377017/test-if-executable-exists-in-python) that `parallel` was in the path before submitting a job so that you don't waste time submitting a job that is going to fail almost surely.

Same goes for `qsub` and `qstat` although missing these would lead to an immediate failure so not nearly as important.

**Comment by gdevenyi** [comment]
Gotta be careful to check for "local" mode, since it doesn't need qsub/qstat
