### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by pipitone** [pipitone/qbatch#48]
i've tagged [v1.0rc1](https://github.com/pipitone/qbatch/releases/tag/v1.0rc1) and pushed to [pypi](https://pypi.python.org/pypi?:action=display&name=qbatch&version=1.0rc1). Give it a go and we can work out any blockers in this version and aim to release 1.0 at the end of the week. 

btw, I'm pushing a proper release because I have projects I want to integrate this with.

**Comment by pipitone** [comment]
i've tagged [v1.0rc2](https://github.com/pipitone/qbatch/releases/tag/v1.0rc2) and pushed to [pypi](https://pypi.python.org/pypi?:action=display&name=qbatch&version=1.0rc2).

**Comment by gdevenyi** [comment]
Will update and get feedback from users.

**Comment by pipitone** [comment]
What do you think? Time to let the world know about our kewl tool? :-)

**Comment by gdevenyi** [comment]
One more rc with the python3 and individual jobs stuff? I haven't run that in production yet.

**Comment by gdevenyi** [comment]
Also #75 should be gone over quickly before a final release

**Comment by gdevenyi** [comment]
All standing PRs not WIP merged. rc4 tagged.

**Comment by pipitone** [comment]
Gabe, do you have a user on pypi? I'll add you as an owner so you can push releases there.

**Comment by gdevenyi** [comment]
I don't. When I do it will be a google login for gdevenyi@gmail.com

**Comment by gdevenyi** [comment]
Google login is borked, username for pypi is gdevenyi

**Comment by pipitone** [comment]
Cool beans. You are now an owner. Can you also create an account on https://testpypi.python.org so I can make you owner there also (you can push to testpypi first to make sure everything checks out before the real deal. It's important because you can't remove or resubmit versions from pypi.)

**Comment by gdevenyi** [comment]
Done. Same username.

**Comment by pipitone** [comment]
You have been blessed by the testpypi gods.

**Comment by pipitone** [comment]
Okay, the 1.0 release is out:
 - https://github.com/pipitone/qbatch/releases/tag/v1.0
 - https://pypi.python.org/pypi/qbatch/1.0

for future reference, here's how I did made the release (via [here](https://packaging.python.org/en/latest/distributing) and [here](https://wiki.python.org/moin/TestPyPI)): 
```sh
$ python setup.py sdist bdist_wheel
$ twine upload -r pypitest dist/*    # to test the release
$ twine upload -r pypi dist/*           
```
