### ISSUE TITLE
Some cosmetic changes to the UI

### ISSUE THREAD

**Issue by pipitone** [pipitone/qbatch#49]
Some feedback from a potential user about the UI: 
- [x] Move `--ppn` and `--mem` from the advanced section to the general section since they are likely to be used often. 
- [x] Move `--workdir` and `--logdir` to advanced section, because they are unlikely to be used often. 
- [x] Create long options for `-c` as `--chunksize` and `-j` as `--jobs` (or, because that's confusing with our terminology `--cores`). 
- [x] Set the default for `-j` to be `100%` and `--ppn` to be `1` rather than arbitrary settings
- [x] Change `--afterok_pattern` to just `--afterok` to simplify
- [x] Change `-w/--workdir` to `-d/--workdir` to be consistent with qsub, and so that we can... 
- [x] Change `-t/--walltime` to `-w/--waltime` to more memorable (and because accidentally setting `-w 4:00:00` doesn't complain, it just creates a folder called `4:00:00` which is disorientating)
- [x] [Print more detailed usage when the command is run without arguments](http://stackoverflow.com/questions/4042452/display-help-message-with-python-argparse-when-script-is-called-without-any-argu)

@gdevenyi, any opinions?

**Comment by gdevenyi** [comment]
Maybe ppn should be ppn? Aka processes per job? 

Ppn doesn't make sense outside of PBS,  or even for PBS setups which job=node? 

I will ask for feedback from my users.

**Comment by gdevenyi** [comment]
Err ppn should be ppj

**Comment by pipitone** [comment]
Re: --ppn as --ppj, requested processors per job. I think that makes
sense. I was treating ppn in pbs and slots in SGE as roughly equivaent.

**Comment by pipitone** [comment]
See branch [ui_cosmetics](https://github.com/pipitone/qbatch/tree/ui_cosmetics) for wip.

**Comment by gdevenyi** [comment]
Hrm was just thinking, perhaps chunks should default to ppj?

**Comment by pipitone** [comment]
> Hrm was just thinking, perhaps chunks should default to ppj?

Yeah, it's a good question as to what sensible defaults are. Really, ppj
== j == chunksize for the vanilla cases. 

Were you thinking that if you set --ppj=10 that chunk size is
automatically set to 10 unless otherwise specified?

**Comment by gdevenyi** [comment]
Yes

**Comment by pipitone** [comment]
> > Were you thinking that if you set --ppj=10 that chunk size is
> > automatically set to 10 unless otherwise specified?
>
> Yes

Ah. Dependencies in default values between options are a bit kludgy with
argparse, but we do it the logdir option already... I'm torn. :-)

**Comment by gdevenyi** [comment]
Oh yeah, that thing again.

I was thinking in terms of just setting it to the same environment var.

P.S. CIC users up and going with 1.0rc1 with ui changes. No reports of issues thus-far

**Comment by pipitone** [comment]
i've incorporated UI changes into master.

**Comment by gdevenyi** [comment]
Nice, looks good. Now I'll need to rebate some PRs :-)
