### ISSUE TITLE
Feature idea: memory specification

### ISSUE THREAD

**Issue by gdevenyi** [pipitone/qbatch#5]
Allow specification of memory in a generic way between job systems.

**Comment by pipitone** [comment]
+1 as I'm not a huge fan of the current `highmem` business. That said, I think in general we should be very conservative about which options we want to handle ourselves, generically, and instead, for the most part, allow the caller to specify these things for their scheduling system. Memory use seems clean enough (I think...) that it should be doable.

**Comment by gdevenyi** [comment]
Yeah the highmem is a scinet-only hack.

In general for memory we need:
- command-line specification for memory
- the variable to request (in the case of SGE, h_vmem vs virtualfree vs mem_free)
- how to handle "total job memory" vs "memory per thread"

Torque:
``-l mem=20mb``

All lower case here

SGE
``-l h_vmem/mem_free/virtualfree=20M``
Suffix without B

**Comment by pipitone** [comment]
Do you think #28 (arbitrary options) would do for this? (i.e. let's not make a qbatch interface for memory spec, but leave it up to the user to take care of)

**Comment by gdevenyi** [comment]
The problem with relying on arbitrary options is that if I use qbatch in a pipeline I need to hack on the pipeline, rather than qbatch, to support a new batch system.

My thought here is to add all basic functionality as options, so that the transformation to a given batch system happens inside qbatch.

**Comment by pipitone** [comment]
> My thought here is to add all basic functionality as options, so that
> the transformation to a given batch system happens inside qbatch.

Yeah, I agree to an extent. I don't want us to run into a situation
where we try to abstract away too much across all queueing systems and
end up with a rat's nest of options on qsub. At some point, we need to
draw the line and leave certain complexities of individual queuing
systems up to the pipeline writers. My key use case for qbatch is to a
tool humans from the command-line, not a unified queue interface. Is
that what you're envisioning? 

All that said, I definitely agree that memory management is critical for
everyone so it's worth take a stab at abstracting as long as we can keep
it simple. 

What about this. We create a --mem option for setting the memory needed by
each *job* (i.e. the sum of all tasks running per scheduled job, be it
an individual job or an element of an array job). We can use this to set
some sensible default qsub options (e.g. h_vmem for SGE), but make it
clear in the code where sysadmins can customize which specific options
are set because of --mem, if needed.

**Comment by gdevenyi** [comment]
I agree this is about as far as complexity needs to go, walltime and memory and this tool is ready to swap in for all my and my user's workloads as well as any pipelines which need cluster integration. As you may have noticed, most of my feature adding has been ensuring it *can* be used for scripting.

It sounds like you're proposing some maths inside qbatch to handle memory specification? I'm all for that, as different batch systems have insane choices for memory specification, we should try and sanitise a little bit.

Any thoughts on how to handle the memory request variable? another environment variable?

**Comment by pipitone** [comment]
I was thinking --mem would be exactly what is set for h_vmem, leaving the calculations up to the user, but you are probably more familiar with the different queuing systems and their madness so if you can think of use cases where internal calculations can be done usefully we can attempt it. 

As for which memory variable(s) to set, yeah let's continue to use an environment variable to set default and an option to override. How about QBATCH_MEM_VARS and the option --mem_vars.

**Comment by gdevenyi** [comment]
Environment variable sounds good.

I re-read your statement above, so you're saying memory per job. That's fine with me too. Either way, we might need to do math for some queuing system, because some expect mem per CPU slot (SGE) while I think others expect memory per job.

**Comment by pipitone** [comment]
I think we need to define our terminology before we go any further. Here's a stab at it:

- command or task: a call to a command line program or script

- command list: a list of commands that qbatch reads in and figures out how to submit to a queueing system.

- job script: a script which qbatch builds to run the commands in the command list, and submits to the queueing system

- job: the submitted job script that's being handled by the queueing system. For array jobs, there is one job script but separate jobs for each element of the array.

- chunk (`-c`): the set of commands from the command list that qbatch batches up and runs as part of each job.

- processes (`-j`): the number of commands that will run in parallel in each job. If the chunk size is smaller than `-j` then only `-c` commands will run in parallel

- cores or processors per node (`--ppn`): the number of cores each job requests. Cores can be over subscribed if `-j` is larger than `--ppn` (which is useful when making use of hyper-threading)

**Comment by gdevenyi** [comment]
I like, we should definitely update the docs to match that, that's very clear.

One tweak:
- chunk (``-c``): the number of commands from the command list that are wrapped into each job.

**Comment by pipitone** [comment]
I've updated the help to a clearer description of the terms.

**Comment by gdevenyi** [comment]
Looks good. This should go in the readme for our users to understand our definitions.

**Comment by pipitone** [comment]
Cooking this in the [memspec](https://github.com/pipitone/qbatch/tree/memspec) branch. Send comments and PRs.
