### ISSUE TITLE
Support other script formats?

### ISSUE THREAD

**Issue by gdevenyi** [pipitone/qbatch#50]
zsh etc?

**Comment by pipitone** [comment]
Hmm.. interesting. Actually, I think if we stick to sh-compatible shell code then it will run fine on sh, bash, zsh, ksh should a user *really* need to switch shells manually. I wouldn't want to get into a situation where we attempt to support idiosyncratic *sh dialects though.

Anyhow, unless you have a good use case for supporting alternate shells, I'm going to say we don't bother with this flexibility for now. I'm going to close this issue, but we can reopen it if needs be.

**Comment by gdevenyi** [comment]
Hrm good point.

Is export supported in all posix shells or is it a bashism. Need to check
that .
