### ISSUE TITLE
Allow for other shells

### ISSUE THREAD

**Issue by gdevenyi** [pipitone/qbatch#56]

**Comment by gdevenyi** [comment]
Make sure we're only using posix shell scripts

**Comment by pipitone** [comment]
We could switch to `/bin/sh`

**Comment by andrewjanke** [comment]
Why be prescriptive? Just use the users shell as this will allow them to do things like inline for loops in their preferred style:

https://github.com/andrewjanke/qbatch/blob/master/qbatch#L104

and

https://github.com/andrewjanke/qbatch/blob/master/qbatch#L124

**Comment by gdevenyi** [comment]
Good thought, we have to be careful that our qbatch magics support other shells.

I recall there being some "interesting" interactions between cluster software and the shell types, including what's "allowed" as a shell.

**Comment by gdevenyi** [comment]
This would also fix the "I need to use a login shell" problem we may be experiencing for some users on scinet.

**Comment by gdevenyi** [comment]
Method:

Expose shebang as QBATCH_SHEBANG
Expose as command-line option
Use in header of jobfiles
Use as spawner for single-job commands.
