### ISSUE TITLE
Provide variable QBATCH_THREADS_PER_COMMAND to running jobs

### ISSUE THREAD

**Issue by gdevenyi** [pipitone/qbatch#6]
Multi-threaded code needs some way to run with many threads.

Need to understand interaction between arrays and parallel environments in SGE to get this right.

**Comment by pipitone** [comment]
I'm inclined to leave this up to the user to work out, but if you can think of a not-too-confusing way to manage it from the command line, let's try it.

**Comment by gdevenyi** [comment]
I was thinking something like --threads, which defaults to "1".

Description something like, "number of threads (processes) each job uses".

We would have to modify the job chunking logic a bit to handle this, looks like we could get away with a rounded division of ncores.

**Comment by pipitone** [comment]
I think we run the risk of confusing people with cores, procs, chunk size, and threads. Can you give a more concrete example of what job you envision running that would need threads specified?

**Comment by gdevenyi** [comment]
If I wanted to, for example, give 2 threads per antsRegistration call, or the latest beast which has openmp.

**Comment by gdevenyi** [comment]
I would tag this as "low priority" anywho

**Comment by pipitone** [comment]
Hmm, I'm a little confused. I don't have much experience with openmp, but in the case of `antsRegistration`, wouldn't it just be a matter of setting the `-j` option when calling `antsRegistration` and then accounting for that when you set the `-j` option on `qbatch`? i.e. if each command uses 2 threads and you have 8 cores to play with per node, you set `-j 4` on `qbatch`? 

Or are you suggesting the `--threads` option is what `qbatch` uses to *compute* an appropriate `-j`, essentially?

**Comment by gdevenyi** [comment]
Hrm, I see what you mean.

I'm going to refine the idea a bit here.

I think qbatch should compute an "available threads per job" value based on the number of parallel jobs running and the number of CPUs available in a job submission.

This could be used in the jobscript to set the OPENMP threads environment variable, or the ITK threads environment variable (or other places) to set the job threading.

**Comment by pipitone** [comment]
Okay, I see where you are going with this. What about having qbatch set and environment variable with this value, e.g. QBATCH_THREADS_PER_COMMAND. Then either commands in the header of the job script or commands themselves could use this value in whatever way needed. 

Actually, I'd like to do this with all of the options to qbatch (e.g. chunk size) in case commands could use this info, and also because it would make the job scripts a bit more self-documenting.

**Comment by gdevenyi** [comment]
That sounds like a great idea.

**Comment by gdevenyi** [comment]
QBATCH_THREADS_PER_COMMAND = floor(QBATCH_PPJ/QBATCH_CORES)
