### ISSUE TITLE
ARRAY_IND should be set with the value of the job array index

### ISSUE THREAD

**Issue by pipitone** [pipitone/qbatch#62]
Looking at the output script in #61 I was reminded of a very minor fix we need to make for clarity.

The fact that this works is a bit magical:
```sh
ARRAY_IND=PBS_ARRAYID
sed -n "$(( (${ARRAY_IND} - 1) * ${CHUNK_SIZE} ...
```

It turns out that `${ARRAY_IND}` expands to the string `PBS_ARRAYID` which inside a `$(( ))` operator gets expanded with its value from the environment. I'd prefer us to do this instead: 
```sh
ARRAY_IND=$PBS_ARRAYID
sed -n "$(( (${ARRAY_IND} - 1) * ${CHUNK_SIZE} ...
```

**Comment by gdevenyi** [comment]
Oh my, that is indeed lucky. Yeah, we should avoid that double expansion.
