### ISSUE TITLE
Handle special case of len(commands) == 1 and len(commands) < chunk_size

### ISSUE THREAD

**Issue by gdevenyi** [pipitone/qbatch#64]
When the length of commands == 1, submitting an array job is inappropriate (and scinet tells me, quite load inducing). Furthermore, using parallel is just overhead.

Should we handle this special case?

My main concern is that if we submit a normal job instead of an array job, we need to figure out the pbs_jobnames search can distinguish between them and set the appropriate afterok code.

**Comment by pipitone** [comment]
Perhaps it makes sense to submit as a normal job if we are only going to submit 1 job (i.e. we have n <= chunk size commands). 

The `pbs_jobnames` issue is something we'll need to handle regardless, right? (i.e. it shouldn't matter what kind of jobs you have when setting up the afterok).

**Comment by gdevenyi** [comment]
Correct,  we should be checking for the type of the afterok job,  as we need to properly handle that. 

Right now,  our code assumes that if you're submitting array jobs,  you're depending on array jobs and if you're submitting single,  you're depending on sine

**Comment by gdevenyi** [comment]
Fixed by PR #72
