### ISSUE TITLE
Make pep8 tests a warning rather than a fail for travis?

### ISSUE THREAD

**Issue by gdevenyi** [pipitone/qbatch#70]
I get bitten every. single. time.

**Comment by pipitone** [comment]
Allow me to introduce you to your new best friend, [`autopep8`](https://pypi.python.org/pypi/autopep8)

**Comment by gdevenyi** [comment]
Glorious!

I wonder if I can make it a pre-checkin hook for my git client...

**Comment by pipitone** [comment]
> I wonder if I can make it a pre-checkin hook for my git client...

Please don't. ;-) It's worth having a look at what it does, and
also running tests.
