### ISSUE TITLE
Implement "batch system options" environment variable

### ISSUE THREAD

**Issue by gdevenyi** [pipitone/qbatch#74]
Administrators may want to specify default settings such as the queue for jobs.
Users may want to specify a priority, project assignment or other for a given batch system.

--options should take in an environment variable if set, QBATCH_OPTIONS or somesuch.

**Comment by pipitone** [comment]
Does the use of `--options` override `QBATCH_OPTIONS` or add to it?

**Comment by gdevenyi** [comment]
It should override.

We should print a warning if you override it though

**Comment by gdevenyi** [comment]
https://bugs.python.org/issue16399

**Comment by gdevenyi** [comment]
Handle after #85
