### ISSUE TITLE
1.0 annoucement

### ISSUE THREAD

**Issue by gdevenyi** [pipitone/qbatch#78]
Places to announce
- cobralab-announce
- minc-users
- scinet list?
- scinet support?

**Comment by gdevenyi** [comment]
software carpentry?

**Comment by gdevenyi** [comment]
mice guys

**Comment by pipitone** [comment]
- camh-scientific-computing

**Comment by gdevenyi** [comment]
http://python.libhunt.com/

**Comment by pipitone** [comment]
Here's some copy we could use to make the announcement (just edit this comment with changes): 

> We'd like to announce `qbatch`, a command-line tool for easily running a list of commands in parallel on a compute cluster. This tool takes the list of commands, divides them up into batches of arbitrary size, and then submits each batch as a separate job or as part of an array job. qbatch also gives you a consistent interface to use to submit commands on PBS and SGE clusters (support for others are planned) or locally, while setting requirements for processors, walltime, memory and job dependencies.
> 
> For more information, check out our github webpage here: http://github.com/pipitone/qbatch

For Scinet people, we could also point them [here](https://wiki.scinet.utoronto.ca/wiki/index.php/User_Serial) to let them know qbatch is an easier way to submit serial jobs.

**Comment by gdevenyi** [comment]
Can I go ahead and start sending this out?

**Comment by pipitone** [comment]
Yeah! Go for it. Thank you. Perhaps make a note here were you've announced so that we don't overlap by accident.

**Comment by gdevenyi** [comment]
Done:
- torque users
- minc-users
- software carpentry
- python libhunt
- MiCe guys (via pydpiper issue)
- scinet

**Comment by gdevenyi** [comment]
Todo:
- [ ] conda
- [ ] tigrlab
- [ ] cobra-announce
- [ ] camh-scientific-computing
- [ ] mice guys proper
