### ISSUE TITLE
Feature idea: allow batch system to manage environment

### ISSUE THREAD

**Issue by gdevenyi** [pipitone/qbatch#87]
Give the option for environment to be qbatch stored, batch system stored, or none?

**Comment by gdevenyi** [comment]
I found that CIVET on scinet is broken for non mchakrav users if we manage the environment.

I have no idea why. Something is different between the two.

**Comment by gdevenyi** [comment]
Specifically, the perl magicks that go looking for "registered" programs like autocrop and mincresample can't find them.

**Comment by pipitone** [comment]
Hmm. Okay, I think this is currently possible if you do something like: 

    qbatch --no-env --options "-V" ...

If that's too unwieldy, we could have something like (with better wording, of course): 

    --env {copied,inherited,none}     Determines how your environment is propagated when your
                                      job runs. "copied" records your environment settings in 
                                      the job submission script, "inherited" uses the cluster's 
                                      mechanism for propagating your environment, and "none" 
                                      does not propagate any environment variables. 
                                      [default: copied]

**Comment by gdevenyi** [comment]
I like option 2
