### ISSUE TITLE
Simplified qbatch usage

### ISSUE THREAD

**Issue by pipitone** [pipitone/qbatch#90]
In an older version of qbatch there was a much more simple usage: 

    qbatch [options] <command_file> <chunk_size> <walltime>

This syntactic sugar was good for quick and dirty submissions when you knew the defaults are good. Should we support this? I'm not convinced but I thought I'd toss it out there as an option.

**Comment by gdevenyi** [comment]
This feels like special casing like sge_batch

I'm more in favour of presenting a consistent (with unix principles) interface like we have.

**Comment by gdevenyi** [comment]
Andrew Jankie mentions:

```
qbatch --logfile blah.log -- do_something_args.pl *.mnc
```

This might be a nice way to do it.

**Comment by andrewjanke** [comment]
I think this is a very nice way to do it.

**Comment by pipitone** [comment]
I think you guys are talking about what is described in issue #35. 

This issue is about providing a short cut for submitting a file of commands.

**Comment by pipitone** [comment]
But I agree, using the `--` is fine way of separating qbatch arguments from the single command and its arguments.

**Comment by gdevenyi** [comment]
Oops, yes this discussion should be at #35

**Comment by gdevenyi** [comment]
We shouldn't support this.
