### ISSUE TITLE
Implement --header-file and --footer-file

### ISSUE THREAD

**Issue by gdevenyi** [pipitone/qbatch#93]
Requested by Andrew Jankie,

See examples https://github.com/andrewjanke/qbatch/blob/master/qbatch#L172

My initial thought is to allow insertion via --header-file and --footer-file rather than hard-coding into qbatch

**Comment by andrewjanke** [comment]
Note that this is not straight forward.  I use the:

{

...

} > logfile.log

shell trick to get this to work. This allows you to collect the correct times

See:

   https://github.com/andrewjanke/qbatch/blob/master/qbatch#L148

**Comment by pipitone** [comment]
I like the idea of the header / footers but I'd rather not introduce more options. Perhaps we could tie the header/footers to the --verbose option.

**Comment by gdevenyi** [comment]
Interesting thought. Regardless of that, I think I'd like to add --header-file at least so people can pre-populate a header with things such as module load commands, so they don't have to specify a big list on the command line.

**Comment by gdevenyi** [comment]
Header/footer support now implemented via #109
