### ISSUE TITLE
Check or cleanup job names

### ISSUE THREAD

**Issue by pipitone** [pipitone/qbatch#97]
Currently this can happen:

```sh
$ echo "baz" > foo@bar
$ qbatch foo@bar
Number of commands less than chunk size, building single non-array job
Unable to run job: At ('@') not allowed in objectname.
Exiting.
qsub call returned error code 1
```

It isn't a particularly nice error.

That said, checking that job names conform to the individual queuing systems may be overkill.

Thoughts?

**Comment by andrewjanke** [comment]
https://github.com/andrewjanke/qbatch/blob/master/qbatch#L80

Perhaps I should have just bombed with an error, it's different for different systems though, gridengine job names can't start with a number for instance but this is OK on PBS.

**Comment by gdevenyi** [comment]
I'm not a fan of adding too much checking at the qbatch level, we're handling the error returns of qsub properly, so let's let it complain when things go badly.

I can see checking getting hairy of we start supporting more batch systems...
