### ISSUE TITLE
Fully describe -n option

### ISSUE THREAD

**Issue by andrewjanke** [pipitone/qbatch#98]
Can you consider adding this option?

usage is as such:

   $ qbatch --fake --script my-script.sh --queue all.q -- mincmath ....

The idea is that instead of running the job it just produces the job file. I find this very useful as it gives you a method to quickly create a qsub script with all the correct options that you can then mess with by hand should you be trying to do something more complex. Also very useful for debugging pipes...

Implemented as such:

   https://github.com/andrewjanke/qbatch/blob/master/qbatch#L139

Not sure how you wold handle your case where there would be multiple output scripts given that your default method of operation is on a list of commands. (something that I am yet to get my head around the reasoning for.).

**Comment by pipitone** [comment]
> Can you consider adding this option?

This is essentially what -n is for. The script is output into .qbatch/
but is not submitted to the queue. Does that work for you?

**Comment by andrewjanke** [comment]
Yes it does. I had a look a the commit history and saw chatter about this regarding the name of the directory. I'm in general against creating hidden folders/files in the current directory and tend to put things in $TMPDIR. What happens when you don't have write permission for the current dir?

I guess this one then turns into a documentation request to make it obvious to the user as to what happens on a dry run.

**Comment by gdevenyi** [comment]
@andrewjanke qbatch only outputs multiple scripts if you specify individual jobs instead of array jobs (for a list of commands).

As for the output directory, it's configured via a environment variable, so you can customize https://github.com/pipitone/qbatch/blob/master/bin/qbatch#L23

**Comment by gdevenyi** [comment]
@andrewjanke new docstring in #107 okay?

**Comment by andrewjanke** [comment]
Fine by me
